from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.db import transaction
from packages.models.charge import Charge
from packages.interfaces.cart import Cart
from packages.exceptions import PackageException


class WebhookView(APIView):
    """View to handle post requests to Webhook.

    These requests should be generated by openpay."""

    def post(self, request):
        type = request.data["type"]
        event_date = request.data["event_date"]

        if type.startswith("charge") and "transaction" in request.data:
            _transaction = request.data["transaction"]
            order_id = _transaction["order_id"]
            try:
                cart = Cart()
                with transaction.atomic():
                    cart.confirm_payment(order_id)
                Charge.objects.create(
                    type=type, response=request.data, event_date=event_date)
            except PackageException as e:
                return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)
        return Response({}, status=status.HTTP_200_OK)
