# Generated by Django 4.1.7 on 2023-05-31 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('included', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('VAR', 'Variable'), ('FIX', 'Fixed')], default='FIX', max_length=25)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('monthly_price', models.FloatField()),
                ('yearly_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('response', models.JSONField()),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('fiscal_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('internal_number', models.CharField(max_length=20)),
                ('external_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.CharField(max_length=100)),
                ('mail_cc', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(1, 'Monthly'), (12, 'Yearly')], default=1)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('STORE', 'Store'), ('BANK', 'Bank'), ('MANUAL', 'Manual')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renewal_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('C', 'Cancelled')], default='A', max_length=1)),
                ('order', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.customer')),
                ('payment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.paymentservice')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('mail_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.mailconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('monthly_price', models.FloatField()),
                ('yearly_price', models.FloatField()),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('E', 'Eliminado')], default='A', max_length=1)),
                ('addons', models.ManyToManyField(to='packages.addon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.product')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.addon')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='addon',
            field=models.ManyToManyField(through='packages.PackageAddon', to='packages.addon'),
        ),
        migrations.AddField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.customer'),
        ),
        migrations.AddField(
            model_name='package',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.plan'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField()),
                ('subscription', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('package_data', models.JSONField()),
                ('hash', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_service_id',
            field=models.ManyToManyField(through='packages.ServiceIdentifier', to='packages.paymentservice'),
        ),
    ]
