# Generated by Django 4.1.7 on 2023-05-31 21:28

from django.db import migrations
from packages.migrations.data.data_insertion import operations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = operations  # type: ignore
